### ISSUE TITLE
对接完小爱开发平台后，进入技能正常。进行操作就报错

### ISSUE THREAD

**Issue by fejich** [KillingJacky/xiaoai_hass_bridge#1]
使用环境是 Alpine 系统使用 Docker 跑最新版的 Home Assistant
> https://hub.docker.com/r/homeassistant/home-assistant

直接在容器里边运行的 python main.py
下边是终端记录
```
* Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:18443/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 129-155-634
[2020-03-17 19:43:00,566] DEBUG in main: {'version': '1.0', 'session': {'is_new': False, 'session_id': '557214886216863744_f1dbd839d3ea42079164ba541467eba8', 'application': {'app_id': '557214886216863744'}, 'user': {'user_id': 'NYYzdbKCJ9niPTJfKN2RxA==', 'is_user_login': True, 'gender': 'unknown'}}, 'request': {'type': 0, 'request_id': '609190db1c4e4f598944cef91db81828', 'timestamp': 1584445379102, 'intent': {'query': '打开小工具', 'score': 0.800000011920929, 'complete': True, 'domain': 'openplatform', 'confidence': 1, 'skillType': 'Custom', 'sub_domain': '1017284', 'app_id': '557214886216863744', 'request_type': 'Start', 'need_fetch_token': False, 'slots': '{"intent_name":"Mi_Welcome"}', 'is_qc': False}, 'locale': 'zh-CN', 'slot_info': {'intent_name': 'Mi_Welcome'}, 'is_monitor': True}, 'query': '打开小工具', 'context': {'device_id': 'Y6U/hXGNzI+g86xs2JrQug==', 'user_agent': 'AHC/2.0', 'device_category': 'soundbox', 'in_exp': False}}
192.168.168.122 - - [17/Mar/2020 19:43:00] "POST /hass/dev HTTP/1.1" 200 -
[2020-03-17 19:43:43,733] DEBUG in main: {'version': '1.0', 'session': {'is_new': False, 'session_id': '557214886216863744_f1dbd839d3ea42079164ba541467eba8', 'application': {'app_id': '557214886216863744'}, 'user': {'user_id': 'NYYzdbKCJ9niPTJfKN2RxA==', 'is_user_login': True, 'gender': 'unknown'}, 'attributes': {'sessi_id': '12345'}}, 'request': {'type': 1, 'request_id': 'fc1e36c391054c4bb0da665958e3256b', 'timestamp': 1584445423650, 'intent': {'query': '关闭所有开关', 'score': 0.800000011920929, 'complete': True, 'domain': 'openplatform', 'confidence': 1, 'skillType': 'Custom', 'sub_domain': '1017284', 'app_id': '557214886216863744', 'request_type': 'Intent', 'need_fetch_token': False}, 'locale': 'zh-CN', 'is_monitor': True}, 'query': '关闭所有开关', 'context': {'device_id': 'dpFVft7Xk2fEN2/oSlQLYg==', 'user_agent': 'AHC/2.0', 'device_category': 'soundbox', 'in_exp': False}}
192.168.168.122 - - [17/Mar/2020 19:43:43] "POST /hass/dev HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/config/ai/main.py", line 103, in index
    if datax["request"]["intent"]["is_direct_wakeup"] == True:
KeyError: 'is_direct_wakeup'
```

**Comment by KillingJacky** [comment]
水滴平台的API接口定义已经变更，这个项目不适用了。

**Comment by fejich** [comment]
原来这样子呀。。。
还考虑更新维护吗

最后谢谢你的回复

**Comment by KillingJacky** [comment]
不维护啦，小米好像不太喜欢这样的技能开发
